module.exports = {
  RECEIVE_POST: "RECEIVE_POST",
  RECEIVE_POSTS: "RECEIVE_POSTS",
  RECEIVE_ALL_POSTS: "RECEIVE_ALL_POSTS",
  RECEIVE_NEW_HIGHLIGHT: "RECEIVE_NEW_HIGHLIGHT",
  RECEIVE_NEW_PHOTO: "RECEIVE_NEW_PHOTO",
  ALL_POSTS_LOADED: "ALL_POSTS_LOADED"
}
