# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e03e1dd0e0b4a45224e98f3439cd5a1d88992620cfce2b63edda0fbd626a78d9c8c11823626819ee1c7d4dcac1a9af3e9a29714fa51c6618519409f31f38988e

test:
  secret_key_base: ed53c4b1c5365c72cb4a11f5245b509e0ba6900f0fa1b221012b8cc40284ac500cbb47f9cb70f625bd4b02d7b5bda212eb95754c7c6e13612ed17210fd9188b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
